module(load="imfile" PollingInterval="2")

# Auditd logs
input(type="imfile"
      File="/var/log/audit/audit.log"
      Tag="audit-rn"
      Severity="info"
      Facility="local7"
      PersistStateInterval="100")

# inotify logs
input(type="imfile"
      File="/var/log/honeypot-inotify.log"
      Tag="inotify-rn"
      Severity="info"
      Facility="local7"
      PersistStateInterval="10")

# Falco logs
input(type="imfile"
      File="/var/log/falco/events.log"
      Tag="falco-rn"
      Severity="info"
      Facility="local6"
      PersistStateInterval="10")

# Forward to receiver
local6.* action(type="omfwd" target="RECEIVER_IP" port="514" protocol="tcp"
               action.resumeRetryCount="100"
               queue.type="linkedList" queue.size="50000")
local7.* action(type="omfwd" target="RECEIVER_IP" port="514" protocol="tcp"
               action.resumeRetryCount="100"
               queue.type="linkedList" queue.size="50000")
